[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[[services]]
name = "braid-agent"

[services.variables]
PYTHONPATH = "/app"
PYTHONUNBUFFERED = "1"
PORT = "8000"

# Supabase Configuration
SUPABASE_URL = "https://xmngdcugklkgboeblmbf.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhtbmdkY3Vna2xrZ2JvZWJsbWJmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5MTU2MzEsImV4cCI6MjA3NDQ5MTYzMX0.UfajLBm3r9Xlf6tluLJawOsDH7_4wwZFDc9XgwCdHlw"
SUPABASE_SERVICE_ROLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhtbmdkY3Vna2xrZ2JvZWJsbWJmIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1ODkxNTYzMSwiZXhwIjoyMDc0NDkxNjMxfQ.qnTWGyiRH1QRPU92ffQxMkmUuZ5V1i0CcDk4i2HbEFA"

# Database Configuration  
DATABASE_URL = "${{DATABASE_URL}}"

# AI/LLM Configuration (Anthropic as primary)
ANTHROPIC_API_KEY = "${{ANTHROPIC_API_KEY}}"
# OPENAI_API_KEY = "${{OPENAI_API_KEY}}" # Optional - uncomment if you want to use OpenAI too

# Integration API Keys (add as needed)
GOOGLE_APPLICATION_CREDENTIALS_JSON = "${{GOOGLE_APPLICATION_CREDENTIALS_JSON}}"
SLACK_BOT_TOKEN = "${{SLACK_BOT_TOKEN}}"
NOTION_TOKEN = "${{NOTION_TOKEN}}"
PERPLEXITY_API_KEY = "${{PERPLEXITY_API_KEY}}"
