[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile.librechat"

[deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[[services]]
name = "librechat"

[services.variables]
# LibreChat Configuration
APP_TITLE = "Braid AI Chat"
CUSTOM_FOOTER = "Powered by Braid AI Agent System"
HELP_AND_FAQ_URL = "https://braid-production.up.railway.app/docs"

# Database Configuration (MongoDB for LibreChat)
MONGO_URI = "${{MONGO_URI}}"

# Braid Integration
BRAID_API_URL = "http://braid.railway.internal:8000"
BRAID_API_KEY = "${{BRAID_API_KEY}}"

# Authentication
JWT_SECRET = "${{JWT_SECRET}}"
JWT_REFRESH_SECRET = "${{JWT_REFRESH_SECRET}}"

# OpenAI API (for LibreChat features)
OPENAI_API_KEY = "${{OPENAI_API_KEY}}"

# Social Login (optional)
GITHUB_CLIENT_ID = "${{GITHUB_CLIENT_ID}}"
GITHUB_CLIENT_SECRET = "${{GITHUB_CLIENT_SECRET}}"
GOOGLE_CLIENT_ID = "${{GOOGLE_CLIENT_ID}}"
GOOGLE_CLIENT_SECRET = "${{GOOGLE_CLIENT_SECRET}}"
DISCORD_CLIENT_ID = "${{DISCORD_CLIENT_ID}}"
DISCORD_CLIENT_SECRET = "${{DISCORD_CLIENT_SECRET}}"

# File Upload
ENABLE_FILE_UPLOADS = "true"
FILE_UPLOAD_PATH = "/app/uploads"

# Security
ALLOW_REGISTRATION = "true"
ALLOW_SOCIAL_LOGIN = "true"
ALLOW_SOCIAL_REGISTRATION = "true"

# Custom Endpoints
ENDPOINTS = "braid"

# LibreChat specific
HOST = "0.0.0.0"
PORT = "3080"
DOMAIN_CLIENT = "${{RAILWAY_PUBLIC_DOMAIN}}"
DOMAIN_SERVER = "${{RAILWAY_PUBLIC_DOMAIN}}"
